### ISSUE TITLE
Not working with 2.6.6

### ISSUE THREAD

**Issue by thomasshaw85** [giddie/redmine_default_assign#23]
Hi,

I thought I would give this plugin a go but I cannot get it working on redmine 2.6.6

The following is thrown to the log file.

Started GET "/redmine/projects/complaints/settings" for 10.58.15.43 at 2015-11-04 15:19:40 +0000
Processing by ProjectsController#settings as HTML
  Parameters: {"id"=>"complaints"}
  Current user: shawt (id=1)
  Rendered projects/_form.html.erb (28.9ms)
  Rendered projects/_edit.html.erb (29.9ms)
  Rendered common/_tabs.html.erb (32.0ms)
  Rendered projects/settings.html.erb within layouts/base (32.6ms)
Completed 500 Internal Server Error in 49.8ms

ActionView::Template::Error (undefined method `default_assignee_id' for #<Project:0xc1fbba0>):
    25: <% @project.custom_field_values.each do |value| %>
    26:   <p><%= custom_field_tag_with_label :project, value %></p>
    27: <% end %>
    28: <%= call_hook(:view_projects_form, :project => @project, :form => f) %>
    29: </div>
    30: 
    31: <% if @project.new_record? %>
  lib/redmine/views/labelled_form_builder.rb:38:in`select'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in`each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in`tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:158:in`call_hook'
  app/views/projects/_form.html.erb:28:in `_app_views_projects__form_html_erb___295442028_96405540'
  app/views/projects/_edit.html.erb:2:in`block in _app_views_projects__edit_html_erb__211858186_96354800'
  app/helpers/application_helper.rb:1056:in `labelled_form_for'
  app/views/projects/_edit.html.erb:1:in`_app_views_projects__edit_html_erb__211858186_96354800'
  app/views/common/_tabs.html.erb:22:in `block in _app_views_common__tabs_html_erb___940505001_96227130'
  app/views/common/_tabs.html.erb:21:in`each'
  app/views/common/_tabs.html.erb:21:in `_app_views_common__tabs_html_erb___940505001_96227130'
  app/helpers/application_helper.rb:328:in`render_tabs'
  app/views/projects/settings.html.erb:3:in `_app_views_projects_settings_html_erb___685781069_96110010'
